# Generated by Django 3.2.2 on 2021-05-19 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.FloatField()),
                ('rating', models.IntegerField()),
                ('quatity', models.IntegerField()),
                ('category', models.CharField(max_length=10)),
                ('feedback', models.TextField()),
                ('imgscr', models.URLField()),
                ('unq_id', models.IntegerField(unique=True)),
            ],
        ),
    ]
