# Generated by Django 3.2.2 on 2021-05-19 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecomm', '0002_auto_20210519_1447'),
    ]

    operations = [
        migrations.RenameField(
            model_name='items',
            old_name='quatity',
            new_name='quantity',
        ),
    ]
