# Generated by Django 3.2.2 on 2021-05-20 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecomm', '0003_rename_quatity_items_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='items',
            name='date_sold',
        ),
        migrations.RemoveField(
            model_name='items',
            name='feedback',
        ),
        migrations.RemoveField(
            model_name='items',
            name='site_own',
        ),
    ]
